python3 mlp_zimbrao.py 0
python3 multivariate_mlp_zimbrao.py 0
python3 convolutional_zimbrao.py 0
python3 multivariate_convolutional_zimbrao.py 0
python3 multivariate_conv2d_zimbrao.py 0
python3 lstm_zimbrao.py 0
python3 lstm_zimbrao_stateful.py 0
python3 multivariate_lstm_zimbrao.py 0
python3 multivariate_lstm_zimbrao_stateful.py 0